// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/j2me.proto

package com.google.protobuf.j2me;

public final class J2Me {
  private J2Me() {}
  public static final
    com.google.protobuf.Extension generateBuilder =
      com.google.protobuf.Extension
        .newExtension("com.google.protobuf.DescriptorProtos.MessageOptions",
            com.google.protobuf.WireFormat.FieldType.BOOL,
            50001, false, new java.lang.Boolean(false));
  
  public static final
    com.google.protobuf.Extension keepUnknownFields =
      com.google.protobuf.Extension
        .newExtension("com.google.protobuf.DescriptorProtos.MessageOptions",
            com.google.protobuf.WireFormat.FieldType.BOOL,
            50002, false, new java.lang.Boolean(true));
  
  public static final
    com.google.protobuf.Extension cstyleEnum =
      com.google.protobuf.Extension
        .newExtension("com.google.protobuf.DescriptorProtos.EnumOptions",
            com.google.protobuf.WireFormat.FieldType.BOOL,
            50003, false, new java.lang.Boolean(false));
  
  
  static {
    com.google.protobuf.Extension.register(com.google.protobuf.j2me.J2Me.generateBuilder);
    com.google.protobuf.Extension.register(com.google.protobuf.j2me.J2Me.keepUnknownFields);
    com.google.protobuf.Extension.register(com.google.protobuf.j2me.J2Me.cstyleEnum);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
