// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/j2me.proto

#ifndef PROTOBUF_google_2fprotobuf_2fj2me_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fj2me_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {
namespace j2me {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_google_2fprotobuf_2fj2me_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fj2me_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fj2me_2eproto();


// ===================================================================


// ===================================================================

static const int kGenerateBuilderFieldNumber = 50001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  generate_builder;
static const int kKeepUnknownFieldsFieldNumber = 50002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  keep_unknown_fields;
static const int kCstyleEnumFieldNumber = 50003;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  cstyle_enum;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace j2me
}  // namespace protobuf
}  // namespace google

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fj2me_2eproto__INCLUDED
