// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example1.proto

public final class Example1 {
  private Example1() {}
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
